### PR TITLE
Resolve runtime dependency on setuptools to get version

### LINKED ISSUE #418: [ENH] get rid of setuptools as runtime dependency
## Is your feature request related to a problem? Please describe.

We have identified that we need to have setuptools _at runtime_ in order to have `rdiff-backup --version` spit out the correct version instead of simply `DEV`. Our packagers find that pulling 3MB for this small feature isn't acceptable, on the other hand our developers.

## Describe the solution you'd like

I want all team members to fill well with the solution we choose while not impacting the efficiency and the precious little spent by volunteers to develop rdiff-backup.

## Describe alternatives you've considered

This issue is here for everybody to propose and discuss alternatives.

## Additional context

This is a follow-up enhancement to the issue #305 but is to be considered independently of any specific packaging format (DEB or RPM).

### PR DESCRIPTION
**Pull request by ericzolf**
CHG: depend on importlib-metadata instead of setuptools to get rdiff-backup veersion, closes #418

### CODE REVIEW

**Comment by ericzolf** [comment]
TODO: adapt the documentation once discussion in #418 is done.

**Comment by ericzolf** [comment]
The initial commit had a stupid typo in it, I fixed it forcefully...

**Comment by ikus060** [comment]
Had a look at it. It seams to be the appropriate way to do.

**Comment by ikus060** [comment]
Don't you want to in next release ? Should we merged this ?

**Comment by ericzolf** [comment]
Yes, I want this in the next release. I merge, no issue.

**Pull request merged**
