### PR TITLE
Clean-up the code with pep8 and replace tabs with spaces #60

### PR DESCRIPTION
**Pull request by elMor3no**
Clean-up the code with pep8 and replace tabs with spaces #60

I **don't** fix any issue on the code, only the format and replace tabs

**Need to check some warnings as:**
```
src/rdiff_backup/win_acls.py:305:13: E731 do not assign a lambda expression, use a def
src/rdiff_backup/TempFile.py:45:13: F821 undefined name 'Log'
src/rdiff_backup/TempFile.py:61:13: F821 undefined name 'remove_listing'
src/rdiff_backup/TempFile.py:79:9: F821 undefined name 'remove_listing'
src/rdiff_backup/TempFile.py:83:9: F821 undefined name 'remove_listing'
src/rdiff_backup/statistics.py:133:33: F821 undefined name 'stat_file_attrs'
src/rdiff_backup/statistics.py:135:37: F821 undefined name 'stat_file_attrs'
src/rdiff_backup/statistics.py:136:52: F821 undefined name 'stat_file_attrs'
src/rdiff_backup/statistics.py:245:16: E713 test for membership should be 'not in'
src/rdiff_backup/statistics.py:306:13: F821 undefined name 'StatObj'

```

### CODE REVIEW

**Comment by ericzolf** [comment]
`eas_acls.py` seems to have been forgotten, it still has spaces/tabs issues according to Travis, see job log at https://travis-ci.org/rdiff-backup/rdiff-backup/jobs/603625999?utm_medium=notification&utm_source=github_status -  we can then merge this request, and clean up the rest in another one (I volunteer).

**Comment by elMor3no** [comment]
Oh... My mistake 
Well i can clean up in a couple of day. Now im full...

**Comment by elMor3no** [comment]
Done... :)

**Comment by ericzolf** [comment]
Looks good to me, thanks a lot! We're almost done with #60, I can take over.

**Pull request merged**
