### PR TITLE
Use Globals.set_all instead of SetConnections.UpdateGlobal

### PR DESCRIPTION
**Pull request by ericzolf**
It is more logical to have set_all together with set and set_local.

A simple one, but it depends on #651 and will need to be rebased before it can be merged.

### CODE REVIEW

**Comment by ericzolf** [comment]
I've deprecated  Globals.postset_regexp_local in the same PR to avoid one review, not very clean but who cares?

**Comment by ericzolf** [comment]
A rather simple PR ready for your review...

**Comment by dio4ev** [comment]
I haven't looked at PR #651 yet, but this one looks good from my side.

**Comment by ericzolf** [comment]
Thanks!

**Pull request merged**
