### PR TITLE
Improve logfiles handling

### PR DESCRIPTION
**Pull request by ericzolf**
- revert changes to have the log object passed as parameter to actions and locations, it'll remain a singleton, as it is usual actually.
- make sure log.Log is used everywhere instead of Log
- Use names for log levels and format messages
- Improve further formatting and adapt docs, also ErrorLog (I noticed that its methods were called remotely using backup_writer instead of the usual `conn`)

CHG: all messages have a proper prefix corresponding to their severity (ERROR, WARNING, etc...)

Still TODO adapt CODING docs to changes made

### CODE REVIEW

**Comment by ikus060** [comment]
May I start reviewing or you expect other major changes ?

**Comment by ericzolf** [comment]
I wait only to do documentation changes to avoid clashes, you can already review. Thanks.

**Comment by frankcrawford** [comment]
@ericzolf If you want to merge it in now, I'll pull down the update and roll the two changed files into my update.

I should get it back to you by the end of this weekend.

**Comment by ericzolf** [comment]
I'm not finished with the documentation, I'll finish once you're done, week-end is fine with me.

**Comment by ericzolf** [comment]
OK, the PR is ready for review, I've tried hard to unified and improve the logging as much as I could. I know that there is more to be done, but I'll do it as I go...

Using API 201, the output looks now so:

```
$ PATH=$PWD/build/scripts-3.9:$PATH PYTHONPATH=$PWD/build/lib.linux-x86_64-3.9 python build/scripts-3.9/rdiff-backup -v5 --api-version 201 backup docs /tmp/bak2
*        Using repository '/tmp/bak2'
*        Unable to import win32security module. Windows ACLs not supported by
         filesystem at path docs
-----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
NOTE:    Extended attributes not supported by filesystem at path
         /tmp/bak2/rdiff-backup-data/rdiff-backup.tmp.0 due to exception
         '[Errno 95] Operation not supported'
*        Unable to import win32security module. Windows ACLs not supported by
         filesystem at path /tmp/bak2/rdiff-backup-data/rdiff-backup.tmp.0
-----------------------------------------------------------------
Detected abilities for destination (read/write) file system:
  Ownership changing                           Off
  Hard linking                                 On
  fsync() directories                          On
  Directory inc permissions                    On
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   Off
  Access control lists                         On
  Extended attributes                          Off
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
*        Backup: escape_dos_devices = 0
*        Backup: escape_trailing_spaces = 0
NOTE:    Starting mirror from source path docs to destination path /tmp/bak2
*        Processing file .
*        Processing file CODING.adoc
*        Processing file DEVELOP.adoc
*        Processing file FAQ.adoc
*        Processing file Windows-DEVELOP.adoc
*        Processing file Windows-README.adoc
*        Processing file api
*        Processing file api/README.adoc
*        Processing file api/v200.adoc
*        Processing file api/v201.adoc
*        Processing file arch
*        Processing file arch/README.adoc
*        Processing file arch/classes.svg
*        Processing file arch/locations.adoc
*        Processing file arch/packages.svg
*        Processing file arch/plugins_actions.adoc
*        Processing file arch/rdiff_backup_classes.puml
*        Processing file arch/rdiff_backup_classes.sh
*        Processing file arch/rdiff_backup_classes.svg
*        Processing file credits.adoc
WARNING: Could not determine if source directory docs permits trailing spaces
         or periods in filenames because we can't find any files with trailing
         dot/period. It will be treated as permitting such files
*        Processing file examples.adoc
*        Processing file index.adoc
*        Processing file migration.adoc
*        Processing file rdiff-backup-old.1
*        Processing file rdiff-backup-statistics.1
*        Processing file rdiff-backup.1.adoc
*        Processing file rdiff-backup.1.md
*        Processing file resources
*        Processing file resources/logo-128.png
*        Processing file resources/logo-32.png
*        Processing file resources/logo-32.svg
*        Processing file resources/logo-a.png
*        Processing file resources/logo-a.svg
*        Processing file resources/logo-banner.png
*        Processing file resources/logo-banner.svg
*        Cleaning up
```

It doesn't look as good with the default API 200 but there is only so much I can do while staying compatible.

**Comment by ikus060** [comment]
I did not review the PR yet, but what about the error_log, restore.log and backup.log Is it impacted by this changes ? If so, how is it impacted ?

**Comment by ericzolf** [comment]
The Error log isn"t impacted, the backup / restore log looks similar to the terminal output but without the fancy line breaks ( makes grep & co easier).

**Comment by ericzolf** [comment]
May I ping again? This PR is a bit all over the place and blocks me...

**Comment by ikus060** [comment]
> May I ping again? This PR is a bit all over the place and blocks me...

Will review today.

Have you tested compatibility with API200 vs API201 ? e.g.: running this with rdiff-backup 2.0.5
I feel something is wrong in the `log.Log()` Or I'm missing something.

**Review by ikus060 — APPROVED** [review]

**Comment by ericzolf** [comment]
> Have you tested compatibility with API200 vs API201 ? e.g.: running this with rdiff-backup 2.0.5
> I feel something is wrong in the `log.Log()` Or I'm missing something.

Yes, I did, it looks a bit strange because old and new styles are mixed, but else it works fine.

**Pull request merged**
