### PR TITLE
[DOC] Windows build: 32/64 and linker error explained

### PR DESCRIPTION
**Pull request by rstarkov**
I followed the build instructions and got a difficult to diagnose error. I've explained the cause in these instructions.

I've also modified the instructions to default to the 64 bit build, as that is the recommended python download and is probably what most people have I suspect.

### CODE REVIEW

**Comment by ericzolf** [comment]
Thanks, Roman, looks like a meaningful extension. Can you also extend accordingly the Python 3 chapter? It explicitly only lists the 32 bits version currently, which wouldn't be consistent anymore with your changes.
And, if you don't mind the additional effort to test, it would be nice to bump the Python version to 3.9, which is now the default version for the pipeline (my fault, I oversaw the document as I bumped the version).

**Comment by rstarkov** [comment]
Good idea, this will take some time but I'll do it.

**Comment by ericzolf** [comment]
Any news?

**Comment by rstarkov** [comment]
@ericzolf thanks for your patience with me. I've re-tested everything on python 3.9 and updated obsolete instructions in the python 3 chapter.

**Comment by ericzolf** [comment]
Looks good to me, thanks for not giving up on my (hopefully reasonable :smirk: ) request!

**Pull request merged**
