### PR TITLE
Adding Cross-device link to list of error to ignore #1024

### PR DESCRIPTION
**Pull request by ikus060**
FIX: Continue when encountering Cross-Device link error

## Changes done and why

Adding Cross device link error to the list of robust error.

## Self-Checklist

- [ ] changes to the code have been reflected in the documentation
- [ ] changes to the code have been covered by new/modified tests
- [x] commit contains a description of changes relevant to users prefixed by DOC:, FIX:, NEW: and/or CHG:

### CODE REVIEW

**Comment by ericzolf** [comment]
The timeout after 360m/6h starts to get on my nerves, I've reported it at https://github.com/orgs/community/discussions/141132. You might want to vote it up.

Anyway see discussion in #1024 (this issue should have been linked with a `Closes #1024` at the end of the `FIX:` message!)

**Comment by ikus060** [comment]
@ericzolf Here my first attempt to better handle Cross Device Link error.

I also remove the "move()" function that is not used anywhere.

**Review by ericzolf — APPROVED** [review]

**Comment by ericzolf** [comment]
The change looks good, I have approved but this timeout issue on our pipeline is killing me (and this is a bad joke, because I suspect the issue in the `kill_test.py`). I'll try to fix this before merging this PR.

**Comment by ericzolf** [comment]
Merged, thanks for the effort and patience!

**Pull request merged**
