### PR TITLE
Adapt setup-testfiles.sh to handle new location for test files

### LINKED ISSUE #54: Decide where to store test files
The next Tox framework uses test files from https://github.com/ericzolf/rdiff-backup/releases

Where should we host this in the future?

Options:
- in gh-pages branch as a tar.gz for download via rdiff-backup.net/testfiles.tar.gz to keep the master branch / main repo "clean" from binary stuff
- in master branch as a tar.gz and ensuring the test suite and the test data evolve lockstep in the same commits
- somewhere else?

Alternatively, do we even have to have the files as a binary package? Could it be stored in an uncompressed plain files way in the master branch and then some kind of test-prepare.sh script would set the file permissions and attributes (since git does not store them and the special attributes is required for the test files, as that is almost the whole point in them).

### PR DESCRIPTION
**Pull request by ericzolf**
The test files tar ball is now in the rdiff-backup-filesrepo Git repo.
Move also the script to the tools sub-directory.
Closes #54

### CODE REVIEW

**Comment by ericzolf** [comment]
Can someone validate my choice?

**Comment by ericzolf** [comment]
@afoster @ikus060 even if you can't merge, can you please review and tell me your opinion in absence of @ottok ? It's a rather important change and I'd like to be sure I don't oversee anything before I merge the PR.

**Comment by ericzolf** [comment]
I allow myself to merge without feedback, we can still change the location if we find a better solution, and at least I'm not anymore the only one able to modify the files, so I think the situation improved even if it's not perfect.

**Comment by afoster** [comment]
Sorry for the late reply @ericzolf , I have no problem with this.

**Pull request merged**
