### PR TITLE
Use python3 instead of python

### LINKED ISSUE #973: [BUG] Removal of setup.py usage in debian/autobuild.sh regressed it
## Bug summary

In commit cddb923 the title is to stop using setup.py. However, the commit message only lists the changes. There is no explanation of *why* the change was made as [typically git commit messages should](https://optimizedbyotto.com/post/good-git-commit/) have.

The file `setup.py` itself was however not removed. Thus just wondering, it the project going to use Python setuptools or not?

## What happened and what did you expect?

I came across this while trying to run:

```
± make dist_deb
podman run --rm -i -v /home/otto/koodia/rdiff-backup/rdiff-backup/..:/build/ -w /build/rdiff-backup rdiff-backup-dev:debian-sid debian/autobuild.sh
/usr/bin/env: 'python': No such file or directory
```

I reverted the change back to make it work again:

```diff
-VERSION="$(./tools/get_project_metadata.py Version)"
+VERSION="$(./setup.py --version)"
```

Seems project still uses setuptools and the setuptools API works just as expected.

### PR DESCRIPTION
**Pull request by ericzolf**
## Changes done and why

FIX: use python3 instead of python in all scripts, as it seems more common, closes #973

This contradicts the LSB at https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Languages/LSB-Languages/pylocation.html but seems to be the pragmatic choice.

## Self-Checklist

- [x] changes to the code have been reflected in the documentation
- [x] changes to the code have been covered by new/modified tests
- [x] commit contains a description of changes relevant to users prefixed by DOC:, FIX:, NEW: and/or CHG:

### CODE REVIEW

**Comment by ericzolf** [comment]
@ottok can you please review if this fixes your issue?

**Comment by ericzolf** [comment]
> This contradicts the LSB at https://refspecs.linuxbase.org/LSB_5.0.0/LSB-Languages/LSB-Languages/pylocation.html but seems to be the pragmatic choice.

Aha: [Debian discontinued LSB support in 2015](https://wiki.debian.org/LSB).

**Comment by frankcrawford** [comment]
FYI, Fedora are also discussing discontinuing LSB support as well.

**Comment by ericzolf** [comment]
No reaction and it sounds innocuous enough, so merging.

**Pull request merged**
