### PR TITLE
Publish rmv-from-backup script

### PR DESCRIPTION
**Pull request by ikus060**
Contribution from Robert Nichols
https://lists.nongnu.org/archive/html/rdiff-backup-users/2019-12/msg00005.html
Script to delete files and directory from a rdiff-backup repository.

### CODE REVIEW

**Comment by ericzolf** [comment]
Did you check that it works with a backup repo created by the latest version of rdiff-backup?

**Comment by rdiff-backup-admin** [comment]
@ikus060 you seem to have overseen that I had asked a question.

**Comment by ikus060** [comment]
@ericzolf I've seen it forgot to answer. 
I've test. it's working on a small repository. But like any of the script present in `tools/misc` I would not recommend it for production. Like, I would recommend to do a backup of the repository. aka a backup of the backup. lol

In mid January I will work on a real solution to safely delete a file or a directory.

So my recommendation is to merge this as of now and supply a better alternative in the future

**Comment by ericzolf** [comment]
Agreed, just wanted to be sure it somehow works. I'll merge once the PR has finished rebasing.

**Pull request merged**
