### PR TITLE
Fix missing modules in Windows binary

### PR DESCRIPTION
**Pull request by ericzolf**
I had basically to do two things to address #731

1. downgrade PyInstaller from 5.2/5.3 to 5.1
2. downgrade Python 3.10.7 to 3.10.5

Note that I won't close the issue with this PR, I consider this to be only a workaround and hope to find a better solution during the beta phase.

### CODE REVIEW

**Comment by ericzolf** [comment]
OK, this is ready for review, we're back to 3.10.7, which was important from a security perspective. Getting PyInstaller back to a newer version will take more effort, something for another PR.

**Comment by ericzolf** [comment]
OK, now really no more changes. Please review that we can merge and release a new working beta version.

**Comment by ericzolf** [comment]
OK, sorry, the circular dependency was much easier to fix than I thought, so I've created PR #734 which makes this PR obsolete.

**Comment by ericzolf** [comment]
Bah, change leads to an error in the tests, so back to this PR, I'll fix the other one later on. It's now more important that we get more feedback on the beta.

**Comment by ikus060** [comment]
Not sure what is the difference with #734

**Comment by ericzolf** [comment]
It's only a workaround because I couldn't use PyInstaller > 5.1, #734 _additionally_ removes a circular dependency so that PyInstaller continues to work.

**Comment by ericzolf** [comment]
And, now, after reviewing your comments on #734, I understand better your confusion. :shrug: I've got it sorted.

**Pull request merged**
