### PR TITLE
handle sparse files efficiently

### PR DESCRIPTION
**Pull request by seife**
This patch is originally from Erich Wheeler, posted on the mailing list
http://lists.gnu.org/archive/html/rdiff-backup-users/2011-01/msg00000.html
I ported it forward and amended it to work with GzipFile output.

This patch has been shipping in the openSUSE rdiff-backup package since 2014, so it is quite field-tested ;-)

### CODE REVIEW

**Comment by ericzolf** [comment]
As much as I like the sparse file handling, I don't really like the "short reads" optimization: it avoids perhaps a few writes but it's IMHO compensated by copying the code between inbuf and buf, and it makes the code a lot more complex.

I think that without this short read handling, you can get rid of the buf variable and avoid half of the additional code. Can you have a take at it?

As a side note, I'm very hesitant at adding new features to our current beta, but no issues once 2.0.0 is out (hopefully soon).

**Comment by seife** [comment]
I actually took offense on that buf handling, too, but I'm just a casual python hacker, so I forwarded more or less the original patch.

The only thing I could imagine is, that this should avoid creating sparse "holes" smaller than blocksize. But then, the whole thing is not blocksized aligned anyway, and in the end the file system will have to handle such things. I'll get rid of the buf and short-reads handling and test this in the openSUSE package, then resubmit.

**Comment by ikus060** [comment]
Take note recent filesystem like BTRFS and ZFS are making this patches completely useless.
> As a side note, I'm very hesitant at adding new features to our current beta, but no issues once 2.0.0 is out (hopefully soon).
Same here. This patches was not part of Debian build. Let keep it aside

**Comment by seife** [comment]
I'd rather use anything else than BTRFS and won't switch to Solaris or BSD any time soon ;-)

But out of interest: do BTRFS and ZFS not handle sparse files anymore? I know NTFS doesn't, but I don't care so much about that.

**Comment by ikus060** [comment]
My point is more, many Filesystem are supporting sparse file out of the box. Without the user telling anything. I know ZFS does it very well when compression is enabled.

**Comment by seife** [comment]
with compression it probably just compresses the zeroes, and the file is not really sparse afterwards.

Anyway, there are enough linux file systems that can benefit from this ;-)

**Comment by ericzolf** [comment]
XFS and ext4 are still all over the place indeed. I'll look at the new patch later, have to work for real now.

**Comment by seife** [comment]
We can postpone this until after the release of 2.0,
I'll expose it to some testing in the openSUSE package until then.

**Comment by ericzolf** [comment]
Can you please merge master back into your branch and push it? Somehow I can't do it myself from the WebUI. I'll merge then. Thanks.

**Comment by seife** [comment]
I rebased on master instead of merging, that saves us one merge commit ;-)

**Comment by ericzolf** [comment]
Well, it doesn't matter too much as we squash and we did it a lot like you in the past, but in PR #255 I proposed to change our approach for some reasons, hopefully good ones. Have a look and let me know there what you think.

Anyway, merging! Thanks.

**Comment by seife** [comment]
To be honest, I did not know about the possibility to squash PRs and (of course ;-) ) I did no tread the documentation before submitting my patches. Will do so in the future.

**Pull request merged**
