### PR TITLE
Mark internal functions, classes and variables with underscore

### PR DESCRIPTION
**Pull request by ericzolf**
This is a rather big pull request, and probably the first one of a series of code improvement PRs.

I still need to review myself the PR and make sure I didn't oversee anything, but I'd appreciate if you could review it in parallel.

It's a lot of individual commits, roughly one for each module file, renaming all variables/functions/classes internal to the module and/or internal to a class with an underscore as prefix to the name. I decided that it doesn't count if such functions/variables are used by the testing code.

Let me know if you prefer to have one big commit to review or if the current state is OK for you.

### CODE REVIEW

**Comment by ikus060** [comment]
Ping me when this Mr is ready for review. Look promissing.

**Comment by ericzolf** [comment]
It's actually ready for review, I'm just still reviewing it myself because it's so big and I marked it as draft to make sure that it won't get merged by mistake before we release the next bug-fix.

**Comment by ericzolf** [comment]
FYI, addresses issue #294

**Comment by ericzolf** [comment]
May I interject that I can't continue programming until this PR is merged?

**Comment by ikus060** [comment]
This is a huge PR. I've scan trough all of it and all seams good for me. Cross finger we are not breaking anything.
We still don't have inter-compatibility test in our pipeline.

**Comment by ericzolf** [comment]
Agreed, I did some smoke tests locally, but it's not the same. Nevertheless I've paid attention to not rename functions going over the connection, so I see a limited risk.

**Pull request merged**
