### PR TITLE
Reshuffle main function to allow for programmatic usage

### LINKED ISSUE #703: [ENH] Documentation for using rdiff-backup as a module
The documentation details how to use rdiff-backup as a CLI tool.
I could not find any documentation regarding using rdiff-backup as a module in a python project.
Of course one can spawn a subprocess using the CLI interface, but that seems like a waste and makes interpreting the output very clunky.
Imagine you have a project which establishes a SSH connection via Paramiko and as a subtask needs to invoke rdiff-backup.
It would be nice if this could just be some call `rdiff_backup.backup(ssh_client, local_path, key_value_options_mirroring_cli_interface, progress_callback)`.

My questions:

- is there already a way to achieve this functionality?
- is the module itself documented anywhere?

### PR DESCRIPTION
**Pull request by ericzolf**
NEW: define (imperfect) programmatic usage of rdiff-backup, see FAQ for details, closes #703

### CODE REVIEW

**Comment by ikus060** [comment]
I was actually, using the following code to call rdiff-backup
```
        # Execute the command line.
        logging.debug(_('executing command: %s') % _sh_quote(args))
        try:
            cwd = os.getcwd()
            ld_path = os.environ.get('LD_LIBRARY_PATH')
            if ld_path:
                del os.environ['LD_LIBRARY_PATH']
            os.chdir('..')
            with redirect_ouput(logger):
                # We need to avoid settings signal handlers.
                rdiff_backup.robust.install_signal_handlers = lambda: None
                rdiff_backup.Main.Main(args)
        except SystemExit as e:
            logging.error('rdiff-backup exit with non-zero code')
            raise_exception(e)
        finally:
            os.chdir(cwd)
            if ld_path:
                os.environ['LD_LIBRARY_PATH'] = ld_path
```

Do we have alpha version or something similar so I could run integration test with rdiff-backup > 2.0.5 ?

**Comment by ericzolf** [comment]
There are few of  them already, but I can make one more once the PRs are merged.

**Comment by ericzolf** [comment]
BTW, as admin, you can simply create a branch with a name ending with an underscore and push it. Git Hub will then create a draft release from which you can download the artefacts, After that, you just remove branch and release.

**Comment by ericzolf** [comment]
@ikus060 do you give me a review, or that was it?

**Comment by ikus060** [comment]
I'm good with your changes even if it's probably brake my stuff.  :(

**Comment by ericzolf** [comment]
Sorry for this, but better do it in a controlled manner than by surprise. Regarding revamping your code, two suggestions:

1. wait until we've come into the beta phase, it shouldn't be too long now, I expect only one more PR to do a last refactorization.
2. take the chance to use the new CLI interface, so that you don't need twice to touch your code once the old CLI will have been removed.

Now let me fix this pesky merge error...

**Comment by ikus060** [comment]
> Sorry for this, but better do it in a controlled manner than by surprise. Regarding revamping your code, two suggestions:
> 
> 1. wait until we've come into the beta phase, it shouldn't be too long now, I expect only one more PR to do a last refactorization.
> 2. take the chance to use the new CLI interface, so that you don't need twice to touch your code once the old CLI will have been removed.
> 
> Now let me fix this pesky merge error...

I'm using CLI interface and pure python call depending of my need. Either way, I will need to change my code.

Keep me posted when you enter in Beta. I will not some time to ensure Minarca and Rdiffweb are supporting the new version.

**Pull request merged**
