### PR TITLE
Make sure tox.ini doesn't write if called without venv

### LINKED ISSUE #949: [ENH] make tox.ini only write to readable places with --current-env
## What is it about?

When trying to add a `%check` option to RPM spec file, using the current `tox.ini` file it attempts to write to a directory that it does not have permission to do, i.e. `open("{envsitepackagesdir}/coverage.pth","w")`

## Version, Python, Operating System

Current github version, i.e. 2.4.1+

## rdiff-backup call

Adding the following to rdiff-backup RPM fails:

```
%check
%tox
```

Causes a failure on writing:

```
+ /usr/bin/python3 -m tox --current-env -q --recreate -e py311
rdiff-backup 2.4.1.dev14+gf27110de3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.11/site-packages/coverage.pth'
py311: exit 1 (0.01 seconds) /builddir/build/BUILD/rdiff-backup-weekly> python -c 'with open("/usr/lib/python3.11/site-packages/coverage.pth","w") as fd: fd.write("import coverage; coverage.process_startup()\n")' pid=1235
  py311: FAIL code 1 (0.19 seconds)
  evaluation failed :( (0.21 seconds)
error: Bad exit status from /var/tmp/rpm-tmp.HDMejv (%check)
    Bad exit status from /var/tmp/rpm-tmp.HDMejv (%check)

```

The question is `tox.ini` suitable for use for an RPM `%check`, or what can be used, and should it be attempting to write to that directory?

### PR DESCRIPTION
**Pull request by ericzolf**
## Changes done and why
NEW: tox.ini supports --current-env as normal user, avoiding to write in root-protected paths, closes #949

## Self-Checklist

- [x] changes to the code have been reflected in the documentation
- [x] changes to the code have been covered by new/modified tests
- [x] commit contains a description of changes relevant to users prefixed by DOC:, FIX:, NEW: and/or CHG:

### CODE REVIEW

**Comment by frankcrawford** [comment]
@ericzolf okay, good news is that that patch seems to work fine and it runs %check step.
Bad news is that it fails one or more of the checks.
```
Error processing line 1 of /builddir/.local/lib/python3.11/site-packages/coverage.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 186, in addpackage
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'coverage'

Remainder of file ignored
test_utils_simpleps (__main__.UtilsPsutilTest.test_utils_simpleps)
verify that hardlinked files can be rotated, see issue #272 ... ERROR

======================================================================
ERROR: test_utils_simpleps (__main__.UtilsPsutilTest.test_utils_simpleps)
verify that hardlinked files can be rotated, see issue #272
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rdiff-backup-weekly/testing/utils_simpleps_test.py", line 31, in test_utils_simpleps
    self.assertIn(simpleps._get_pid_name_ps(os.getpid()).split(".")[0],
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILDROOT/rdiff-backup-2.4.1.dev14+gf27100d-1.fc38.x86_64/usr/lib64/python3.11/site-packages/rdiffbackup/utils/simpleps.py", line 54, in _get_pid_name_ps
    output = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ps'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
/usr/lib64/python3.11/site-packages/coverage/inorout.py:507: CoverageWarning: Module rdiff_backup was never imported. (module-not-imported)
  self.warn(f"Module {pkg} was never imported.", slug="module-not-imported")
py311: exit 1 (0.08 seconds) /builddir/build/BUILD/rdiff-backup-weekly> coverage run testing/utils_simpleps_test.py --verbose --buffer pid=11059
  py311: FAIL code 1 (30.18 seconds)
  evaluation failed :( (30.21 seconds)
error: Bad exit status from /var/tmp/rpm-tmp.IJHwNx (%check)
    Bad exit status from /var/tmp/rpm-tmp.IJHwNx (%check)
```

However, I also noticed that the `ModuleNotFoundError: No module named 'coverage'` occurs in most of the tests, but does not cause a fatal error.

**Comment by ericzolf** [comment]
Mmh, of course, coverage must be installed...

**Comment by frankcrawford** [comment]
Okay, I'll guess `coverage` would come in as a `BuildRequires`.

I've never played with `tox`, etc before, so am learning about how this testing works.

However, the rest of the test failure does seem to indicate an issue about something else (`ps`) not being found, which is strange, because it exists, maybe another RPM that needs to be pulled in.

**Comment by ericzolf** [comment]
OK, this raises a few points:

1. tox.ini calls `coverage` which each command, and that doesn't seem to be an issue, but then coverage.pth doesn't find the `coverage` module. How does this difference happen?
2. add coverage to the BuildRequires, yes, probably necessary.
3. the `ps` command isn't found, which means that
    a. the (optional) `psutil` module isn't installed, which is fine (it's optional)
    b. but also that the `ps` utility isn't in the PATH, what is its value in a Fedora build environment? Or is `ps` really not installed in the environment?
    c. you need to "BuildRequire" either python3-psutil or procps-ng and/or add it to the PATH (or I need to call `/usr/bin/ps` instead of simply `ps`).
4. you really need to tell me how to progress, there seems to be a lot of assumptions not holding in your packaging environment.
5. if you prefer, or additionally, I'm welcoming Fedora packaging instructions for dummies to reproduce your packaging environment so that I can test myself what's exactly happening.

**Comment by frankcrawford** [comment]
Sorry, still working through this, but:

1. `coverage` is automatically included when I included `tox` for checking.  I am trying to work out why coverage.pth doesn't fine the module.  I think it may be a lib vs lib64 issue.
2. Not actually necessary, it is done automatically
3. Yes, I've added a `BuildRequires: /bin/ps` as it was not automatically pulled into the `chroot`'ed environment.
4. Working on why `/builddir/build/BUILD/rdiff-backup_testfiles/stattest1` doesn't exist.  It seems to be done externally to the rest of the setup.
5. Probably what I currently need to find is a successful `tox` run, so I can compare it to the results I am getting.

I'm fine just working through it, I'm learning a lot.

**Comment by frankcrawford** [comment]
@ericzolf well, I kind of know what is wrong with `coverage` now.  When `coverage.pth` is run, not all site paths are setup.  If I replace it with `import sys; print('\n'.join(sys.path))` I get
```
/usr/lib64/python311.zip
/usr/lib64/python3.11
/usr/lib64/python3.11/lib-dynload
/builddir/.local/lib/python3.11/site-packages
```
but at a later stage I get
```
/usr/lib64/python311.zip
/usr/lib64/python3.11
/usr/lib64/python3.11/lib-dynload
/builddir/.local/lib/python3.11/site-packages
/usr/lib64/python3.11/site-packages
/usr/lib/python3.11/site-packages
```

I don't know when or how the extras get added, but will explore that further.

And obviously `coverage` is in `/usr/lib64/python3.11/site-packages`.

**Comment by ericzolf** [comment]
Few things and thoughts (in a time crush) before I forget:

1. the file `/builddir/build/BUILD/rdiff-backup_testfiles/stattest1` needs to be unpacked, check `.github/workflows` on how we do it.
2. I could place the pth file at the end of the paths list, instead of the start, but I'm not sure it would solve all possible combinations.
3. https://github.com/fedora-python/tox-current-env states that dependencies aren't installed, which explains a lot of our issues

I'm thinking if we shouldn't create a tox_smoke.ini without coverage and dependency on https://github.com/rdiff-backup/rdiff-backup-filesrepo

**Comment by frankcrawford** [comment]
Okay, will look at the workflow and can probably workout some spec file setup equivalent, but I am also thinking that the full test suite may be overkill for the RPM build anyway.  A cut-down version may be a better option.

Also, this isn't really too urgent as it is more for either the weekly or future dev builds, not the current release.

**Comment by ericzolf** [comment]
OK, I added a `tox_smoke.ini` file, so that you should be able to call `tox -c tox_smoke.ini ...` to have only tests without coverage and without need for pre-existing test files. Let me know if this works.

**Comment by frankcrawford** [comment]
Thanks, I will try it in the next few days.

**Comment by frankcrawford** [comment]
@ericzolf  I tried it, and in general it works, but there are some issues with `tox_smoke.ini`.

Firstly, the script `testing/verbosity_actions_test.sh` still uses `coverage run` for the tests (it works, but doesn't propagate the failures.

Secondly, `testing/api_test.py` fails as follows:

```
AssertionError: {'exec': {'version': '2.4.1.dev14+gf27110de3', 'api_[296 chars]-8'}} != {'exec': {'api_version': {'actual': 201, 'default': [249 chars]38'}}
  {'exec': {'api_version': {'actual': 201,
                            'default': 201,
                            'max': 201,
                            'min': 201},
            'parsed': None,
            'version': '2.4.1.dev14+gf27110de3'},
-  'python': {'executable': '/builddir/build/BUILD/rdiff-backup-weekly/.tox/py312/bin/python',
+  'python': {'executable': '/usr/bin/python3',
              'name': 'cpython',
              'version': '3.12.0'},
   'system': {'fs_encoding': 'utf-8',
              'platform': 'Linux-6.6.5-x86_64-with-glibc2.38'}}
```

Which is correct, since it is using a local version of `python` rather than the system one.

**Comment by ericzolf** [comment]
I've removed the shell script from the ini file, it doesn't add much to smoke tests.
Regarding the python executables, it's a bit weird because I'd expect the test script to run with the same Python as rdiff-backup, but in your case it's a wrong assumption. Anyway, I've simplified the test so that it should pass, as long as the python executable contains `python`. And as I write these lines, I realize that it might not be a good idea under Windows, because of PyInstaller... Running out of time now, I'll check later.

**Comment by ericzolf** [comment]
My suspicion with Windows proved true, hence yet another fix. Let me know if it works now @frankcrawford

**Comment by frankcrawford** [comment]
Okay, updated my spec file with the new tests and it completes fine.  Note, that it basically applies the diff between your test branch and a weekly version from a few weeks ago.

I've attached the build log for you to quickly look through to see if there is any issue you can see that I missed.

[build.log](https://github.com/rdiff-backup/rdiff-backup/files/13778026/build.log)

**Pull request merged**
