### PR TITLE
Fix for #384

### PR DESCRIPTION
**Pull request by JirkaV**

### CODE REVIEW

**Comment by ericzolf** [comment]
Can you please re-create a new PR based on a clean master? Else it's quite confusing, and the risk for merging errors grows.

Regarding the fix itself, it's very coarse, I'm not convinced that we can accept it. The failure in the tests seems genuine to me, meaning that your change caused it.

**Comment by ottok** [comment]
@JirkaV Please rebase on latest master so we can review and merge this. Thanks!

**Comment by ericzolf** [comment]
As I already wrote above, the patch isn't acceptable in its current state, we're still working on identifying the root cause and find a better patch. No need to refresh now.

**Comment by ottok** [comment]
Submitter never followed up on this, so closing now.

Thanks for your steps towards contributing. Feel free to take a new shot at solving this at a later time in a new clean PR.

**Pull request closed without merging**
