### PR TITLE
Integrate the new logo into the README Close #286

### LINKED ISSUE #286: Replace rdiff-backup logo
Thanks to @ericzolf rdiff-backup has an icon, but we must admit it's not very professional. I'm working with a designer and I've asked her to create a new logo for rdiff-backup. Something more professional!

Here the results so far, she's waiting for our feedback. @frankcrawford @ottok 

* This version is nice to put in a banner on the website and github README. I may ask for a squared version of the logo if you think it's useful.
*For the colour scheme, she used the blue from the current logo. But the web site if using red. Which one you prefer ? Red or blue ?

Screenshot from 2020-02-25 11-23-20

### PR DESCRIPTION
**Pull request by ikus060**

### CODE REVIEW

**Comment by ikus060** [comment]
@ericzolf @ottok 
Take a look at the new logo. I've also integrate some modification to the README.

**Comment by ikus060** [comment]
I've also took the liberty to update the organisation avatar.

**Comment by ericzolf** [comment]
I'm still not 100% convinced by the new logo but it's gone better so let's start with it. Can you please just remove the old logo at `src/rdiff-backup.svg`.

**Comment by ottok** [comment]
Looks good!

The font in SVG renders a bit different, but maybe it's just Github:
image

**Comment by ottok** [comment]
Suggestion for commit message: 
> Add new logo and improve visual appeal of the README (Closes: #286)

**Comment by ikus060** [comment]
@ottok 
I have update the commit message. About the font it's probably because your Chrome browser doesn't have the font installed or something similar, then it default to other font for the display.
@ericzolf 
I've remove the src/*.svg files

**Pull request merged**
