### PR TITLE
WIP: Reffactoring backup.py

### PR DESCRIPTION
**Pull request by ikus060**
Creating this PR to slowly refactor backup.py to comply with PEP8 without braking anything else

### CODE REVIEW

**Comment by ericzolf** [comment]
Looks so far innocuous to me.

**Comment by ikus060** [comment]
> Looks so far innocuous to me.

ha ha, I will slowly do some changes in backup.py to possibly fix the performance issues with empty diff files when permissions is changing. But the code is so hard to read. Variables with all capital case, like CCCP.

Any how, I'm doing this step by step and might take time. Do you want to to merge at every single step ?

**Comment by ericzolf** [comment]
That the code is hard, I can confirm, that's why I'm reshuffling it currently (and I'm struggling to get the next step).
Anyway, I don't need to merge each single step, I will now concentrate on getting a test pipeline for Windows running, so that I am more free to do bolder changes.

**Comment by ericzolf** [comment]
I think, you can give up on this one, I plan a deeper change (it might take a while though). It will reshuffle quite a lot of stuff, among others the backup file.

**Comment by ikus060** [comment]
+1 I'm quite busy with my own Minarca project.
Closing this MR.

**Pull request closed without merging**
