### PR TITLE
Making rdiff-backup work with Python3

### PR DESCRIPTION
**Pull request by ericzolf**
Not caring anymore about Python2...

### CODE REVIEW

**Comment by ikus060** [comment]
Thanks alot for all the work you put into making rdiff-backup working with python3.

**Comment by ericzolf** [comment]
You're welcome. If someone has some free cycles, I'd appreciate some help as I'm currently stuck with a `Segmentation fault (core dumped)` error, which happens AFAICJ when a delta of a previously existing file needs to be written. Being new to C extensions, I'm finding my way slowly...

**Comment by ericzolf** [comment]
OK, the result seems to work now properly, at least I couldn't find anymore errors after commit 1fa89fa. I want though to have the tests running properly before I merge.

In the meantime, it would be good to have people doing manual tests on their own, like backing up and restoring, and verifying that the result is the same. Also with different types of excludes/includes, Windows/Mac as platform (I can't test those platform so you better give me info), and server based backup as well, would be great. Just create issues and assign them to me and I'll pick them up.

**Comment by ericzolf** [comment]
There are only 3 test scripts left to try/adapt/correct, after which this (huge) pull request could get merged back into master. Is there any interest from the maintainers of this repo to do so, or should I look into maintaining my own repo? In case of no reaction within a reasonable amount of time, I'd go along and decouple my repo from this one.

**Comment by davekempe** [comment]
> There are only 3 test scripts left to try/adapt/correct, after which this (huge) pull request could get merged back into master. Is there any interest from the maintainers of this repo to do so, or should I look into maintaining my own repo? In case of no reaction within a reasonable amount of time, I'd go along and decouple my repo from this one.

This is amazing work Eric. Thank you. Hoping we can check and merge this soon. I will put aside time and get some help from our end.

**Comment by ericzolf** [comment]
No hurry, I'm away from my keyboard for now, but I want to be sure there is someone on the receiving end as there wasn't a lot of activity recently. I'll remove the WiP in the title once I'm the opinion it the PR can be merged. Thanks for reacting so fast!

**Comment by ericzolf** [comment]
With the commit from yesterday, the last test script has been finalized and I don't plan further changes related to Python 3 (unless someone finds a bug).
Please review and accept the pull request. I'd like also to start a discussion on how to release the next version (the branch holds for now a version 1.3.4).

**Comment by ericzolf** [comment]
@davekempe can you or someone able to speak for sol1 join the conversation on the rdiff-backup-users mailing list started by Otto, see https://lists.nongnu.org/archive/html/rdiff-backup-users/2019-07/msg00005.html

As you'll read, we're discussing plans to take ownership of the project and create a community, and I'd prefer to do it in good agreement with you.

(I also wanted to prove I'm the one I said I was)

**Comment by ericzolf** [comment]
As there were some (implicit) questions on the mailing list, few hints on how to test:

```
git clone git@github.com:ericzolf/rdiff-backup.git
cd rdiff-backup
git checkout ericzolf-py2to3
./setup.py build
sudo -i  # optional if you need to be root, then go back to the Git directory
PATH=$PWD/build/scripts-3.7:$PATH PYTHONPATH=$PWD/build/lib.linux-x86_64-3.7 rdiff-backup <all options you want to test>
```

Check for example [backitup3.local.sh.txt](https://github.com/sol1/rdiff-backup/files/3437998/backitup3.local.sh.txt) that I run as root to mimick my regular backup with the glob list
[backitup.lst.txt](https://github.com/sol1/rdiff-backup/files/3438003/backitup.lst.txt)

The documentation README and DEVELOP.adoc gives you more hint on what you can do (tox etc).

**Comment by afoster** [comment]
> As you'll read, we're discussing plans to take ownership of the project and create a community, and I'd prefer to do it in good agreement with you.

Hi Eric, just wanted to acknowledge this comment. I'll be helping to facilitate the handover. I'll respond on the list.

**Comment by ottok** [comment]
I have done some small scale testing and found no issues so far. I have however not been able to review things in detail, but considering the status of the project and the pressing need, I think we should merge this on master now and then continue from there with the plan to finalize the Python 3 rewrite, add CI pipeline and testing, test upgrades, fix everything, maybe add a few new features and then release this as rdiff-backup 2.0.

What do you think?

**Comment by ericzolf** [comment]
I would have agreed last week but given the comments about Unicode vs. Byte paths on the mailing list, give me until end of the week to fix this, and then merge.

**Comment by ottok** [comment]
Merging this now with the motivations stated above.

**Pull request merged**
