### PR TITLE
Fix incorrect filename syntax error under Windows

### LINKED ISSUE #216: rdiff-backup v1.3 has changed default date format in repos on Windows
rdiff-backup on windows is not working when the source and destination is on windows.

Sorry for the french error message. The only Windows I have under my hand is french.
It's failing as follow:
```
C:\Users\vmtest\Desktop>C:\Users\vmtest\Downloads\rdiff-backup-1.4.0b0-win64.exe
 test_base test_destination
Exception '[WinError 123] La syntaxe du nom de fichier, de répertoire ou de volu
me est incorrecte: b'test_destination/rdiff-backup-data/current_mirror.2019-12-1
5T08:36:05-05:00.data'' raised of class '<class 'OSError'>':
  File "rdiff_backup\Main.py", line 384, in error_check_Main
  File "rdiff_backup\Main.py", line 406, in Main
  File "rdiff_backup\Main.py", line 342, in take_action
  File "rdiff_backup\Main.py", line 422, in Backup
  File "rdiff_backup\Main.py", line 609, in backup_final_init
  File "rdiff_backup\Main.py", line 1112, in checkdest_if_necessary
  File "rdiff_backup\Main.py", line 1076, in checkdest_need_check
  File "rdiff_backup\restore.py", line 56, in get_inclist
  File "rdiff_backup\rpath.py", line 1375, in append
  File "rdiff_backup\FilenameMapping.py", line 146, in __init__
  File "rdiff_backup\rpath.py", line 1047, in __init__
  File "rdiff_backup\rpath.py", line 1073, in setdata
  File "rdiff_backup\rpath.py", line 352, in make_file_dict

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 384, in error_check_Main
  File "rdiff_backup\Main.py", line 406, in Main
  File "rdiff_backup\Main.py", line 342, in take_action
  File "rdiff_backup\Main.py", line 422, in Backup
  File "rdiff_backup\Main.py", line 609, in backup_final_init
  File "rdiff_backup\Main.py", line 1112, in checkdest_if_necessary
  File "rdiff_backup\Main.py", line 1076, in checkdest_need_check
  File "rdiff_backup\restore.py", line 56, in get_inclist
  File "rdiff_backup\rpath.py", line 1375, in append
  File "rdiff_backup\FilenameMapping.py", line 146, in __init__
  File "rdiff_backup\rpath.py", line 1047, in __init__
  File "rdiff_backup\rpath.py", line 1073, in setdata
  File "rdiff_backup\rpath.py", line 352, in make_file_dict
OSError: [WinError 123] La syntaxe du nom de fichier, de répertoire ou de volume
 est incorrecte: b'test_destination/rdiff-backup-data/current_mirror.2019-12-15T
08:36:05-05:00.data'
[3504] Failed to execute script rdiff-backup
```

Had a look at the code and I don't find anything obvious about why the "current_mirror.2019-12-15T
08:36:05-05:00.data" is not quoted.

### PR DESCRIPTION
**Pull request by ericzolf**
This error happens when updating a repo created with version 1.2.x
because gathering data was done before quoting the filename containing
a column in the RORPath->RPath->QuotedRPath hierarchy.

Closes #216

### CODE REVIEW

**Comment by ericzolf** [comment]
Attached the deployed draft Windows binary: [rdiff-backup-1.4.0b1.dev25+gba3f836.zip](https://github.com/rdiff-backup/rdiff-backup/files/4021821/rdiff-backup-1.4.0b1.dev25%2Bgba3f836.zip) - please test that it solves #216 and #218

**Comment by pblahman** [comment]
My test fails to produce a backup.    It does create a "rdiff-backup-data" folder in "H:/RdiffBackupStuff"
C:\Users\JackieLahman\Downloads\rdiff-backup-1.4.0b1.dev25+gba3f836>rdiff-backup.exe C:/Users H:/RdiffBackupStuff
Exception 'readlink() argument 1 must be str, not bytes' raised of class '<class 'TypeError'>':
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\rpath.py", line 1375, in append
  File "rdiff_backup\rpath.py", line 1047, in __init__
  File "rdiff_backup\rpath.py", line 1073, in setdata
  File "rdiff_backup\rpath.py", line 374, in make_file_dict

Exception 'readlink() argument 1 must be str, not bytes' raised of class '<class 'TypeError'>':
  File "rdiff_backup\Main.py", line 390, in error_check_Main
  File "rdiff_backup\Main.py", line 412, in Main
  File "rdiff_backup\Main.py", line 348, in take_action
  File "rdiff_backup\Main.py", line 424, in Backup
  File "rdiff_backup\fs_abilities.py", line 1050, in backup_set_globals
  File "rdiff_backup\fs_abilities.py", line 705, in get_readonly_fsa
  File "rdiff_backup\fs_abilities.py", line 133, in init_readonly
  File "rdiff_backup\fs_abilities.py", line 553, in set_resource_fork_readonly
  File "rdiff_backup\selection.py", line 138, in Iterate_fast
  File "rdiff_backup\selection.py", line 122, in diryield
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\rpath.py", line 1375, in append
  File "rdiff_backup\rpath.py", line 1047, in __init__
  File "rdiff_backup\rpath.py", line 1073, in setdata
  File "rdiff_backup\rpath.py", line 374, in make_file_dict

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 390, in error_check_Main
  File "rdiff_backup\Main.py", line 412, in Main
  File "rdiff_backup\Main.py", line 348, in take_action
  File "rdiff_backup\Main.py", line 424, in Backup
  File "rdiff_backup\fs_abilities.py", line 1050, in backup_set_globals
  File "rdiff_backup\fs_abilities.py", line 705, in get_readonly_fsa
  File "rdiff_backup\fs_abilities.py", line 133, in init_readonly
  File "rdiff_backup\fs_abilities.py", line 553, in set_resource_fork_readonly
  File "rdiff_backup\selection.py", line 138, in Iterate_fast
  File "rdiff_backup\selection.py", line 122, in diryield
  File "rdiff_backup\robust.py", line 35, in check_common_error
  File "rdiff_backup\rpath.py", line 1375, in append
  File "rdiff_backup\rpath.py", line 1047, in __init__
  File "rdiff_backup\rpath.py", line 1073, in setdata
  File "rdiff_backup\rpath.py", line 374, in make_file_dict
TypeError: readlink() argument 1 must be str, not bytes
[70736] Failed to execute script rdiff-backup

**Comment by ikus060** [comment]
rdiff-backup-1.4.0b1.dev25+gba3f836.zip on a Windows7 doesn't work.

image

Probably something wrong with the travis build.

**Comment by ericzolf** [comment]
> rdiff-backup-1.4.0b1.dev25+gba3f836.zip on a Windows7 (without upgrades) doesn't work.

Windows 7 is out-of-support in 9 days, do we really care?

**Comment by ericzolf** [comment]
@pblahman sorry, stupid me, the bugfix isn't in this branch. Still need to get used to the automated build mechanism... Let me try something and come back to you.

**Comment by ericzolf** [comment]
I'll merge then based on feedback from https://github.com/rdiff-backup/rdiff-backup/issues/216#issuecomment-570807170

**Comment by ikus060** [comment]
> > rdiff-backup-1.4.0b1.dev25+gba3f836.zip on a Windows7 (without upgrades) doesn't work.
> 
> Windows 7 is out-of-support in 9 days, do we really care?

I will have plenty of users with Windows 7. I'm probably not unique.

**Comment by ericzolf** [comment]
Regarding Win7, the solution is here: https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows and doesn't seem to be a rdiff-backup issue but a "not patched system" issue. Can you please try? And then we can find a place to document this, FAQ or Windows README.

**Comment by ikus060** [comment]
I could give a try, but to be honest, I would prefert to build the executable as you did before. I don't have any problem running this exe: https://github.com/rdiff-backup/rdiff-backup/releases/download/v1.4.0.beta/rdiff-backup-1.4.0b0-win64.exe

What is the differences ?

**Comment by ericzolf** [comment]
So, shall I merge?

**Comment by ikus060** [comment]
> So, shall I merge?

Yes !

**Pull request merged**
