### PR TITLE
Fix issue with function in debug mode

### PR DESCRIPTION
**Pull request by ericzolf**
## Changes done and why

FIX: TypeError failure on class function with debug verbosity at level 8 or 9

## Self-Checklist

- [x] changes to the code have been reflected in the documentation
- [x] changes to the code have been covered by new/modified tests
- [x] commit contains a description of changes
    * relevant to users prefixed by DOC:, FIX:, NEW: and/or CHG:
    * relevant to the web-site prefixed by WEB:
    * relevant to developers prefixed by DEV:

### CODE REVIEW

**Comment by ericzolf** [comment]
@frankcrawford this is the fix for the bug I found, would you prefer to apply your own patch or shall I release asap 2.2.1?

**Comment by frankcrawford** [comment]
@ericzolf  your call.  It is easier to wait for 2.2.1, but I can apply the patch easily as well.

I assume it also affects other OS too, but I guess they haven't yet been packaged there.

**Comment by frankcrawford** [comment]
P.S. I assume it is only `rpath.py` I need to patch for the distribution?

**Comment by ericzolf** [comment]
> @ericzolf your call. It is easier to wait for 2.2.1, but I can apply the patch easily as well.
> 
> I assume it also affects other OS too, but I guess they haven't yet been packaged there.

Yeah, good point, let me release 2.2.1 asap.

> P.S. I assume it is only `rpath.py` I need to patch for the distribution?

Correct.

**Comment by frankcrawford** [comment]
FYI, I've applied the patch to the COPR build and that is available now.

**Pull request merged**
