### PR TITLE
Fix check for proper parent directory inclusion in include/exclude options

### LINKED ISSUE #22: No error raised in certain occasions when excluding files the wrong way
This bug in the input options check was originally reported on the mailing list here:
https://lists.nongnu.org/archive/html/rdiff-backup-users/2017-01/msg00005.html

In this example the software correctly throws an error, because the excluded file is not specified correctly:
```
$ mkdir temp
$ touch temp/file.txt
$ touch temp/picture.jpg
$ rdiff-backup --exclude file.txt temp backup
Fatal Error: Fatal Error: The file specification
    'file.txt'
cannot match any files in the base directory
    'temp'
Useful file specifications begin with the base directory or some
pattern (such as '**') which matches the base directory.
```

But in certain cases this check fails and no error is printed even if the exclusion is not valid, like in this:
```
$ mkdir temp
$ cd temp
$ mkdir .one
$ mkdir .two
$ mkdir three
$ mkdir four
$ rdiff-backup --exclude .one --exclude ./.two --exclude ./three . ../backup
$ ls -a ../backup
.  ..  four  .one  rdiff-backup-data
```

or in this:
```
$ mkdir temp
$ touch temp/file.txt
$ touch temp/temp.txt
$ rdiff-backup --exclude temp.txt temp backup
$ ls backup
file.txt  rdiff-backup-data  temp.txt
```

### PR DESCRIPTION
**Pull request by ilario**
Fixes #22

### CODE REVIEW

**Comment by ottok** [comment]
Thanks for contributing to rdiff-backup!

As you might have noticed, the project has been stale for some years now. We intend to revitalize it now. I hope you can be involved in the effort!

The biggest ongoing change is the rewrite to Python 3 (in https://github.com/rdiff-backup/rdiff-backup/pull/40) and once that is merged we will have to ask you to rebase this contribution on the new Python 3 code base. Thanks for understanding and your help!

**Comment by ilario** [comment]
I'm following the discussion on the ML and I'm excited about the re-activation of the development!
I'll happily rebase the PR once #40 is merged :)
Thanks!
Ilario

**Comment by ottok** [comment]
Hello!

Most of the code base is now rewritten in Python 3. We also have a CI pipeline now. Could you please rebase this PR on the latest upstream master?

We would also be very grateful if you want to contribute to the project fixing other issues as well besides this PR.

**Comment by ilario** [comment]
Updated in #137

**Pull request closed without merging**
