### PR TITLE
Refactor the regress action

### PR DESCRIPTION
**Pull request by ericzolf**
This led to the need to rename and formalize the action.repo and
action.dir, and some re-shuffling of backup and restore (because
they use regress methods).

I also fixed a few errors in the action tests.

### CODE REVIEW

**Comment by ericzolf** [comment]
@ikus060 as you've been so fast to answer in the recent past, I assume that it was an oversight.

**Comment by ikus060** [comment]
> @ikus060 as you've been so fast to answer in the recent past, I assume that it was an oversight.

I'm trying to keep up the review. I don't want it to stop your development. 

Since all your latest changes are refactoring the new actions, those are fast to review.

**Comment by ericzolf** [comment]
I meant with my remark that you probably oversaw this PR because you reviewed the other one, created at almost the same time.

**Review by ikus060 — APPROVED** [review]

**Comment by ericzolf** [comment]
Thanks!

**Pull request merged**
