### PR TITLE
Fix generated man page and MacOS librsync

### LINKED ISSUE #807: >=rdiff-backup 2.2.0: please provide generated manpages in the release tarballs
Newer releases do not include most manpages in tree and rely on asciidoctor to build them.

For releases, this means depending on a ruby stack to regenerate identical files.
As reference, here is the list of packages pulled in in a Gentoo server for the added dependency:
```
[ebuild  N     ] app-eselect/eselect-ruby-20191222 
[ebuild  N     ] dev-libs/libyaml-0.2.5  USE="-doc -static-libs -test" 
[ebuild  N     ] dev-lang/ruby-2.7.7  USE="berkdb ipv6 rdoc ssl -debug -doc -examples -gdbm -jemalloc -jit -rubytests -socks5 -static-libs -systemtap -tk -xemacs" 
[ebuild  N     ] virtual/ruby-ssl-11  RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/rubygems-3.1.6  USE="-server -test" RUBY_TARGETS="ruby27" 
[ebuild  N     ] virtual/rubygems-16  RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/rake-13.0.3-r1  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/power_assert-1.1.7  USE="-doc -test" RUBY_TARGETS="ruby27" 
[ebuild  N     ] dev-ruby/did_you_mean-1.4.0  USE="-test" RUBY_TARGETS="ruby27" 
[ebuild  N     ] dev-ruby/net-telnet-0.2.0-r1  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30) (-ruby31)" 
[ebuild  N     ] dev-ruby/minitest-5.14.4  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/test-unit-3.3.9  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/json-2.5.1-r1  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/kpeg-1.1.0-r1  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/racc-1.6.0  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30) (-ruby31)" 
[ebuild  N     ] dev-ruby/rdoc-6.3.2  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/bundler-2.1.4  USE="doc -test" RUBY_TARGETS="ruby27" 
[ebuild  N     ] dev-ruby/webrick-1.7.0  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
[ebuild  N     ] dev-ruby/xmlrpc-0.3.2-r1  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30) (-ruby31)" 
[ebuild  N     ] dev-ruby/asciidoctor-2.0.16  USE="-doc -test" RUBY_TARGETS="ruby27 (-ruby30)" 
```

As a workaround, I have patched setup.py to skip these parts and manually install manpages generated on another system.
So  it would be easier if release tarballs included these files.

### PR DESCRIPTION
**Pull request by ericzolf**
## Changes done and why

FIX: man pages are pre-generated from asciidoc to avoid one dependency at package time and avoid trying to package librsync.dll under MacOS, closes #807
CHG: the man pages generated from asciidoc are available under dist/ instead of build/

## Self-Checklist

- [ ] changes to the code have been reflected in the documentation
- [ ] changes to the code have been covered by new/modified tests
- [ ] commit contains a description of changes
    * relevant to users prefixed by DOC:, FIX:, NEW: and/or CHG:
    * relevant to the web-site prefixed by WEB:
    * relevant to developers prefixed by DEV:

### CODE REVIEW

**Comment by ikus060** [comment]
Make sens !

**Comment by Schamschula** [comment]
I applied the patch and now I see the following error:

> creating build
> templating tools/rdiff-backup.spec.template-fedora -> build/rdiff-backup.fedora.spec
> templating docs/rdiff-backup-old.1.template -> dist/rdiff-backup-old.1
> error: [Errno 2] No such file or directory: 'docs/rdiff-backup-old.1.template'
> Command failed:  cd "/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_python_rdiff-backup/rdiff-backup/work/rdiff-backup-2.2.0" && /opt/local/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 setup.py --no-user-cfg build -j20 
> Exit code: 1

**Comment by ericzolf** [comment]
Did your patch also rename `docs/rdiff-backup-old.1` to `docs/rdiff-backup-old.1.template` ?

**Comment by Schamschula** [comment]
The unified patch should have done this. It didn't. I added a `post-patch` script, and all is well.

**Pull request merged**
