### PR TITLE
fix windows 64bit librsync issue

### LINKED ISSUE #453: Fail with MemoryError on Windows 64 bits using stattest
It has even nothing to do with the testcase, I can reproduce the issue with the following snippet under Windows:

```
rdiff-backup ..\rdiff-backup_testfiles\stattest1 \temp\bla
rdiff-backup ..\rdiff-backup_testfiles\stattest2 \temp\bla
```

Or vice-versa, no difference: the first call succeeds, the 2nd one fails.

_Originally posted by @ericzolf in https://github.com/rdiff-backup/rdiff-backup/issues/347#issuecomment-674368766_

```
vagrant@WIN-4SPEID5E7R8 C:\Users\vagrant\Develop\rdiff-backup>rmdir /s /q \temp\bla

vagrant@WIN-4SPEID5E7R8 C:\Users\vagrant\Develop\rdiff-backup>rdiff-backup ..\rdiff-backup_testfiles\stattest1 \temp\bla

vagrant@WIN-4SPEID5E7R8 C:\Users\vagrant\Develop\rdiff-backup>rdiff-backup ..\rdiff-backup_testfiles\stattest2 \temp\bla
Exception '' raised of class '<class 'MemoryError'>':
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\robust.py", line 35, in check_common_error    
    return function(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Rdiff.py", line 98, in patch_local
    return outrp.write_from_fileobj(patchfile)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rpath.py", line 1462, in write_from_fileobj   
    copyfileobj(fp, outfp)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rpath.py", line 79, in copyfileobj
    inbuf = inputfp.read(blocksize)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\librsync.py", line 69, in read
    self._add_to_outbuf_once()
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\librsync.py", line 98, in _add_to_outbuf_once 
    self.eof, len_inbuf_read, cycle_out = self.maker.cycle(self.inbuf)

Exception '' raised of class '<class 'MemoryError'>':
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 399, in error_check_Main
    _Main(arglist)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 421, in _Main
    return_val = _take_action(rps)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 358, in _take_action
    action_result = _action_backup(rps[0], rps[1])
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 445, in _action_backup
    backup.Mirror_and_increment(rpin, rpout, _incdir)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 55, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 281, in patch_and_increment
    ITR(diff.index, diff)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rorpiter.py", line 313, in __call__
    last_branch.fast_process(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 781, in fast_process
    if self._patch_to_temp(mirror_rp, diff_rorp, tf):
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 617, in _patch_to_temp
    elif not self._patch_diff_to_temp(basis_rp, diff_rorp, new):
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 669, in _patch_diff_to_temp
    self.error_handler, Rdiff.patch_local, (basis_rp, diff_rorp, new))
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\robust.py", line 35, in check_common_error
    return function(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Rdiff.py", line 98, in patch_local
    return outrp.write_from_fileobj(patchfile)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rpath.py", line 1462, in write_from_fileobj
    copyfileobj(fp, outfp)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rpath.py", line 79, in copyfileobj
    inbuf = inputfp.read(blocksize)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\librsync.py", line 69, in read
    self._add_to_outbuf_once()
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\librsync.py", line 98, in _add_to_outbuf_once
    self.eof, len_inbuf_read, cycle_out = self.maker.cycle(self.inbuf)

Traceback (most recent call last):
  File "C:\Users\vagrant\Develop\rdiff-backup\build\scripts-3.7\rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 399, in error_check_Main
    _Main(arglist)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 421, in _Main
    return_val = _take_action(rps)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 358, in _take_action
    action_result = _action_backup(rps[0], rps[1])
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Main.py", line 445, in _action_backup
    backup.Mirror_and_increment(rpin, rpout, _incdir)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 55, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 281, in patch_and_increment
    ITR(diff.index, diff)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rorpiter.py", line 313, in __call__
    last_branch.fast_process(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 781, in fast_process
    if self._patch_to_temp(mirror_rp, diff_rorp, tf):
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 617, in _patch_to_temp
    elif not self._patch_diff_to_temp(basis_rp, diff_rorp, new):
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\backup.py", line 669, in _patch_diff_to_temp
    self.error_handler, Rdiff.patch_local, (basis_rp, diff_rorp, new))
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\robust.py", line 35, in check_common_error
    return function(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\Rdiff.py", line 98, in patch_local
    return outrp.write_from_fileobj(patchfile)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rpath.py", line 1462, in write_from_fileobj
    copyfileobj(fp, outfp)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\rpath.py", line 79, in copyfileobj
    inbuf = inputfp.read(blocksize)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\librsync.py", line 69, in read
    self._add_to_outbuf_once()
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-3.7\rdiff_backup\librsync.py", line 98, in _add_to_outbuf_once
    self.eof, len_inbuf_read, cycle_out = self.maker.cycle(self.inbuf)
MemoryError
```

### PR DESCRIPTION
**Pull request by ericzolf**
Closes #453

### CODE REVIEW

**Comment by ericzolf** [comment]
Here is the fixed 64 bits version, it seems to work correctly, volunteers welcome to test:
[rdiff-backup-2.0.6.dev43+g3d37b48-cp37-cp37m-win_amd64.zip](https://github.com/rdiff-backup/rdiff-backup/files/5730424/rdiff-backup-2.0.6.dev43%2Bg3d37b48-cp37-cp37m-win_amd64.zip)

**Comment by ericzolf** [comment]
[rdiff-backup-2.0.6.dev43.win32exe.zip](https://github.com/rdiff-backup/rdiff-backup/files/5731353/rdiff-backup-2.0.6.dev43.win32exe.zip)
This attached file is still 32 bits, just to make sure that the change doesn't break something else.

**Comment by ericzolf** [comment]
Ready for review and merge!

**Comment by ericzolf** [comment]
@dbaarda I would appreciate to get your more knowledgeable opinion about C code.

**Comment by ericzolf** [comment]
Sorry, I allowed myself to merge without review but I needed this to continue working on master.

**Comment by dbaarda** [comment]
Sorry for the late response, but FTR this LGTM.

There may be some improvements that could be made in picking the buffer size based on the job type (sig, delta, patch) and block size, but that's outside the scope of this change and what you have is probably OK.

**Comment by ericzolf** [comment]
Cool, thanks so much for looking into it!

**Pull request merged**
