### PR TITLE
Refactor mapping modules

### PR DESCRIPTION
**Pull request by ericzolf**
DEV: mapping modules (filenames quoting, hardlinks, longnames and owners users/groups) have been moved to locations/map package for better encapsulation
DEV: generic user/group functions have been moved to utils/usrgrp
CHG: remove the possibility to change chars-to-quote between backup calls, this feature never really worked properly anyway

### CODE REVIEW

**Comment by ikus060** [comment]
Will need some time to review this.

**Comment by dio4ev** [comment]
Me too, but I still had not much time to dig into the implementation. 
Thus I don't know how valuable my reviewing is...however I will for sure look over it :)

**Comment by ericzolf** [comment]
fair enough, as long as I know that someone is taking care.

**Comment by ericzolf** [comment]
I don't want to complain or put undue pressure, but it's been 17 days...

**Comment by dio4ev** [comment]
Sorry for the delay, but as far as I can tell ffrom my side the PR looks fine.

**Comment by ericzolf** [comment]
Thanks, I appreciate the help, there are a few more PRs in the meantime (easier to much easier to review though).

**Pull request merged**
