### PR TITLE
remove support for python v2 from rdiff-backup-delete

### PR DESCRIPTION
**Pull request by fireartist**
was broken with python 2.7

### CODE REVIEW

**Comment by ikus060** [comment]
If it's working for you. I'm fine with your changes

**Comment by ericzolf** [comment]
Looks good to me as well. Would you mind perhaps creating a test case for rdiff-backup-delete, we're missing at least one? It could be as part of this PR or in a separate one, as you wish.

**Comment by ikus060** [comment]
@ericzolf Don't we have these tests already ?
https://github.com/rdiff-backup/rdiff-backup/blob/master/testing/rdiffbackupdeletetest.py

**Comment by ericzolf** [comment]
My bad, I was convinced of the contrary. We're even better than I thought! 🤗 Then let's merge! Thanks @fireartist

**Comment by ikus060** [comment]
Perfect !

Thanks @fireartist Your contribution is mush appreciated.

**Pull request merged**
