### PR TITLE
Refactor time functions

### PR DESCRIPTION
**Pull request by ericzolf**
- merge local and remote get_mirror_time functions of repo
- slightly improve get_increment_times and add repo shadow function
- rename repo.init_quoting to setup_quoting to clarify call during setup
- add repo.setup_paths to define default paths of a repository
- slightly clean-up the Time module
- deprecate Time.setprevtime and Time.setprevtime_local
- deprecate Time.setcurtime, replacing with Gloabals variables

### CODE REVIEW

**Comment by ericzolf** [comment]
Ready for your review!

**Comment by dio4ev** [comment]
I am quite occupied at the moment, I will need at least until next week I think.

**Comment by ericzolf** [comment]
Fair enough, I wouldn't complain if @ikus060 finds the time earlier.

**Comment by ericzolf** [comment]
Merged without review...

**Comment by dio4ev** [comment]
Although  already merged, I can't see any problems.

**Pull request merged**
