### PR TITLE
Formating yapf

### PR DESCRIPTION
**Pull request by elMor3no**
I formated all files in misc directory using the **PEP8** format with YAPF tool. 
I correct manually some small format issues in **import section**

### CODE REVIEW

**Comment by ottok** [comment]
Thanks! The code changes look good. I did not test running them though.

You have now fixed ~150 things, that is good! The number of flake8 reported issues dropped from 174 to 23.

Here are the remaining ones:
```
$ docker run -it -v ${PWD}/..:/build -w /build/rdiff-backup rdiff-backup-dev:debian-sid tox -e flake8 | grep misc
./misc/init_files.py:10:1: F401 'stat' imported but unused
./misc/init_files.py:30:22: E701 multiple statements on one line (colon)
./misc/init_files.py:31:5: E701 multiple statements on one line (colon)
./misc/librsync-many-files.py:5:1: F401 'os' imported but unused
./misc/rdiff-backup-delete.py:19:17: E251 unexpected spaces around keyword / parameter equals
./misc/rdiff-backup-delete.py:25:10: E251 unexpected spaces around keyword / parameter equals
./misc/rdiff-backup-delete.py:30:10: E251 unexpected spaces around keyword / parameter equals
./misc/rdiff-backup-delete.py:47:62: W291 trailing whitespace
./misc/rdiff-backup-delete.py:66:75: W291 trailing whitespace
./misc/rdiff-backup-delete.py:67:72: W291 trailing whitespace
./misc/rdiff-backup-delete.py:73:17: E711 comparison to None should be 'if cond is None:'
./misc/rdiff-backup-delete.py:104:95: W605 invalid escape sequence '\.'
./misc/rdiff-backup-delete.py:104:119: W605 invalid escape sequence '\.'
./misc/rdiff-backup-delete.py:126:26: W605 invalid escape sequence '\s'
./misc/rdiff-backup-delete.py:127:22: W605 invalid escape sequence '\s'
./misc/rdiff-backup-delete.py:171:23: W605 invalid escape sequence '\s'
./misc/rdiff-backup-delete.py:171:30: W605 invalid escape sequence '\s'
./misc/rdiff-backup-delete.py:171:34: W605 invalid escape sequence '\s'
./misc/remove-comments.py:18:54: E701 multiple statements on one line (colon)
./misc/remove-comments.py:21:49: E701 multiple statements on one line (colon)
./misc/remove-comments.py:26:16: E701 multiple statements on one line (colon)
./misc/remove-comments.py:28:20: E701 multiple statements on one line (colon)
./misc/remove-comments.py:29:26: E701 multiple statements on one line (colon)
```

Do you want to fix those as well or should we merge the changes done so far?

About git usage: I would recommend that instead of making 6 commits you would use `git rebase -i` and squash them together into one single commit with the commit message "Fix PEP8 issues for misc/ directory (Related: #60)". This way the history is cleaner, the wording is in imperative format and there is a reference to the issue it mostly fixes.

Thanks! :+1:

**Comment by elMor3no** [comment]
> Thanks! The code changes look good. I did not test running them though.
> 
> You have now fixed ~150 things, that is good! The number of flake8 reported issues dropped from 174 to 23.
> 
> Here are the remaining ones:
> 
> ```
> $ docker run -it -v ${PWD}/..:/build -w /build/rdiff-backup rdiff-backup-dev:debian-sid tox -e flake8 | grep misc
> ./misc/init_files.py:10:1: F401 'stat' imported but unused
> ./misc/init_files.py:30:22: E701 multiple statements on one line (colon)
> ./misc/init_files.py:31:5: E701 multiple statements on one line (colon)
> ./misc/librsync-many-files.py:5:1: F401 'os' imported but unused
> ./misc/rdiff-backup-delete.py:19:17: E251 unexpected spaces around keyword / parameter equals
> ./misc/rdiff-backup-delete.py:25:10: E251 unexpected spaces around keyword / parameter equals
> ./misc/rdiff-backup-delete.py:30:10: E251 unexpected spaces around keyword / parameter equals
> ./misc/rdiff-backup-delete.py:47:62: W291 trailing whitespace
> ./misc/rdiff-backup-delete.py:66:75: W291 trailing whitespace
> ./misc/rdiff-backup-delete.py:67:72: W291 trailing whitespace
> ./misc/rdiff-backup-delete.py:73:17: E711 comparison to None should be 'if cond is None:'
> ./misc/rdiff-backup-delete.py:104:95: W605 invalid escape sequence '\.'
> ./misc/rdiff-backup-delete.py:104:119: W605 invalid escape sequence '\.'
> ./misc/rdiff-backup-delete.py:126:26: W605 invalid escape sequence '\s'
> ./misc/rdiff-backup-delete.py:127:22: W605 invalid escape sequence '\s'
> ./misc/rdiff-backup-delete.py:171:23: W605 invalid escape sequence '\s'
> ./misc/rdiff-backup-delete.py:171:30: W605 invalid escape sequence '\s'
> ./misc/rdiff-backup-delete.py:171:34: W605 invalid escape sequence '\s'
> ./misc/remove-comments.py:18:54: E701 multiple statements on one line (colon)
> ./misc/remove-comments.py:21:49: E701 multiple statements on one line (colon)
> ./misc/remove-comments.py:26:16: E701 multiple statements on one line (colon)
> ./misc/remove-comments.py:28:20: E701 multiple statements on one line (colon)
> ./misc/remove-comments.py:29:26: E701 multiple statements on one line (colon)
> ```
> 
> Do you want to fix those as well or should we merge the changes done so far?
> 
> About git usage: I would recommend that instead of making 6 commits you would use `git rebase -i` and squash them together into one single commit with the commit message "Fix PEP8 issues for misc/ directory (Related: #60)". This way the history is cleaner, the wording is in imperative format and there is a reference to the issue it mostly fixes.
> 
> Thanks! +1

I will chechk the 23 other issues... 

And thanks for the recomendation...

**Comment by elMor3no** [comment]
Hi, 
I change this statement but would be nice if someone recheck it
./misc/rdiff-backup-delete.py:73:17: E711 comparison to None should be 'if cond is None:'

i dont touch this one
./misc/rdiff-backup-delete.py:47:62: W291 trailing whitespace
./misc/rdiff-backup-delete.py:104:95: W605 invalid escape sequence '\.'
./misc/rdiff-backup-delete.py:104:119: W605 invalid escape sequence '\.'
./misc/rdiff-backup-delete.py:126:26: W605 invalid escape sequence '\s'
./misc/rdiff-backup-delete.py:127:22: W605 invalid escape sequence '\s'
./misc/rdiff-backup-delete.py:171:23: W605 invalid escape sequence '\s'
./misc/rdiff-backup-delete.py:171:30: W605 invalid escape sequence '\s'
./misc/rdiff-backup-delete.py:171:34: W605 invalid escape sequence '\s'

Hoping the best...

**Comment by ottok** [comment]
Looks good! It's OK not to fix all lines flake8 reports. You have still fixed most of them.

Are you familiar with `git rebase -i`? You could squash all these commits into one single commit.

**Comment by elMor3no** [comment]
> Looks good! It's OK not to fix all lines flake8 reports. You have still fixed most of them.
> 
> Are you familiar with `git rebase -i`? You could squash all these commits into one single commit.

Im not familiar with `git rebase -i` i will read about it and use it on the future...

**Comment by ericzolf** [comment]
Regarding W605, check https://stackoverflow.com/questions/12871066/what-exactly-is-a-raw-string-regex-and-how-can-you-use-it for a lengthy explanation but doubling the backslash is the safest solution. 

Two side notes:
- we can squash & merge ourselves if we want in the github UI
- I've never checked the misc scripts so I don't know what they're doing or if they work with Python 3

**Comment by ottok** [comment]
You have now 10 commits here. With `git rebase -i` I wanted to suggest that this would be squashed to two commits, one for `misc/` and one for `src/`. I will now rebase this on latest upstream master to get the Travis-CI testing as well and then review.

**Comment by ottok** [comment]
```
$ git rebase -i

pick 36ee1e3 Formating using the PEP8 format
pick 8983cbd Formating using the PEP8 format
pick c01b7b0 Formating using the PEP8 format
pick a3b96cc Formating using the PEP8 format
pick 4b9ab7d Delete find2dirs.bck
pick 8c45599 Delete compress-rdiff-backup-increments.bck
pick 23b1b44 Fix PEP8 issues for misc/ directory (Related: #60)
pick a90407a Fix PEP8 issues for misc/ directory (Related: #60)
pick d491f2d Fix PEP8 issues for misc/ directory (Related: #60)
pick 507d10b Fix PEP8 issues for src/rdiff_backup/ directory (Related: #111)

->

pick 36ee1e3 Formating using the PEP8 format
s 8983cbd Formating using the PEP8 format
s c01b7b0 Formating using the PEP8 format
s a3b96cc Formating using the PEP8 format
s 4b9ab7d Delete find2dirs.bck
s 8c45599 Delete compress-rdiff-backup-increments.bck
s 23b1b44 Fix PEP8 issues for misc/ directory (Related: #60)
s a90407a Fix PEP8 issues for misc/ directory (Related: #60)
s d491f2d Fix PEP8 issues for misc/ directory (Related: #60)
pick 507d10b Fix PEP8 issues for src/rdiff_backup/ directory (Related: #111)

->

[detached HEAD cf4bba3] Fix PEP8 issues for misc/ directory (Related: #60)
 Author: mestre <mestre@lambdaforge.io>
 Date: Sun Sep 1 00:44:59 2019 -0300
 10 files changed, 1493 insertions(+), 1324 deletions(-)
 rewrite misc/compress-rdiff-backup-increments (63%)
 rewrite misc/find2dirs (79%)
 rewrite misc/init_files.py (76%)
 rewrite misc/librsync-many-files.py (82%)
 rewrite misc/remove-comments.py (64%)
 rewrite src/rdiff_backup/backup.py (82%)
 rewrite src/rdiff_backup/compare.py (75%)
Successfully rebased and updated detached HEAD.
```
image

The results are here:
https://travis-ci.org/rdiff-backup/rdiff-backup/builds/580069254

image


Unfortunately they did not pass. It should look like on master: https://travis-ci.org/rdiff-backup/rdiff-backup/builds/580068315


Clicking the individual build steps reveals the failures:
```
py37 run-test-pre: commands[0] | python testing/commontest.py
Traceback (most recent call last):
  File "testing/commontest.py", line 9, in <module>
    from rdiff_backup.log import Log
  File "/build/rdiff-backup/.tox/py37/lib/python3.7/site-packages/rdiff_backup/log.py", line 26, in <module>
    from . import Globals, rpath
  File "/build/rdiff-backup/.tox/py37/lib/python3.7/site-packages/rdiff_backup/rpath.py", line 39
    import reimport sys
                      ^
SyntaxError: invalid syntax
```

**Comment by elMor3no** [comment]
Yes... 
Saw the error i will solve now...

**Comment by elMor3no** [comment]
> You have now 10 commits here. With `git rebase -i` I wanted to suggest that this would be squashed to two commits, one for `misc/` and one for `src/`. I will now rebase this on latest upstream master to get the Travis-CI testing as well and then review.

I not sure what i did wrong. I used rebase last time...

**Comment by ottok** [comment]
Builds now passed at https://travis-ci.org/rdiff-backup/rdiff-backup/builds/580685091 (my rebased branch of this PR).

There is still more left to fix all of #60, but this PR does already a big chunck and I will proceed to merge it. Next round of code style fixing can be done in a new PR.

Thanks @elMor3no !

**Comment by ottok** [comment]
Merged via https://github.com/rdiff-backup/rdiff-backup/commit/31c0823597d1360a5e529a84433d2104017fe150 and https://github.com/rdiff-backup/rdiff-backup/commit/d6b7a5e6b7ec9269bb04eb4552e56a803a945359

**Pull request closed without merging**
