### PR TITLE
Dynamically set Debian package version during build

### PR DESCRIPTION
**Pull request by ottok**

### CODE REVIEW

**Comment by ottok** [comment]
Notes:
- writing src/rdiff_backup.egg-info/PKG-INFO is written after the Python byte compilation and file layout moves have run, but before `dh_gencontrol` runs
- `VERSION=$(cd ../; ./setup.py --version)` when invoked from the debian/rules returns nothing or errors

**Comment by ottok** [comment]
Seems that on Ubuntu 18.04 (which e.g. Travis-CI used by default) yields on `/setup.py --version` the error message:
```
your setuptools is too old (<12)
665setuptools_scm functionality is degraded
666/usr/lib/python3/dist-packages/setuptools_scm/git.py:56: UserWarning: "/home/travis/build/rdiff-backup/rdiff-backup" is shallow and may cause errors
667  warnings.warn('"%s" is shallow and may cause errors' % (wd.path,))
668Traceback (most recent call last):
669  File "./setup.py", line 223, in <module>
670    setup_requires=['setuptools_scm'],
671  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
672    return distutils.core.setup(**attrs)
673  File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
674    _setup_distribution = dist = klass(attrs)
675  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in __init__
676    _Distribution.__init__(self, attrs)
677  File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
678    self.finalize_options()
679  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 528, in finalize_options
680    ep.load()(self, ep.name, value)
681  File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 22, in version_keyword
682    dist.metadata.version = get_version(**value)
683  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 125, in get_version
684    local_scheme=local_scheme)
685  File "/usr/lib/python3/dist-packages/setuptools_scm/version.py", line 166, in format_version
686    main_version = version_scheme(version)
687  File "/usr/lib/python3/dist-packages/setuptools_scm/version.py", line 136, in guess_next_dev_version
688    return guess_next_version(version.tag, version.distance)
689  File "/usr/lib/python3/dist-packages/setuptools_scm/version.py", line 108, in guess_next_version
690    bumped = _bump_dev(version) or _bump_regex(version)
691  File "/usr/lib/python3/dist-packages/setuptools_scm/version.py", line 128, in _bump_regex
692    prefix, tail = re.match('(.*?)(\d+)$', version).groups()
```

A more compatible technique is to lookup the version string with `grep -oE "^Version: (.+)$" src/rdiff_backup.egg-info/PKG-INFO | cut -d ' ' -f 2`

**Comment by ottok** [comment]
This is now ready!

**Comment by ericzolf** [comment]
I don't understand the issue you have with setuptools. Bionic has setuptools version 39.1 according to https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=python3-setuptools

**Comment by ottok** [comment]
That error message is in the Travis-CI build logs and I get it locally as well:
```
/rdiff-backup$ sudo apt install python3-setuptools-scm
python3-setuptools-scm is already the newest version (1.15.6-1).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.

rdiff-backup$ sudo apt install python3-setuptools
python3-setuptools is already the newest version (39.0.1-2).
python3-setuptools set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.

rdiff-backup$ ./setup.py --version
your setuptools is too old (<12)
setuptools_scm functionality is degraded
Traceback (most recent call last):
  File "./setup.py", line 223, in <module>
    setup_requires=['setuptools_scm'],
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 528, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3/dist-packages/setuptools_scm/integration.py", line 22, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/usr/lib/python3/dist-packages/setuptools_scm/__init__.py", line 125, in get_version
    local_scheme=local_scheme)
  File "/usr/lib/python3/dist-packages/setuptools_scm/version.py", line 166, in format_version
    main_version = version_scheme(version)
  File "/usr/lib/python3/dist-packages/setuptools_scm/version.py", line 136, in guess_next_dev_version
    return guess_next_version(version.tag, version.distance)
  File "/usr/lib/python3/dist-packages/setuptools_scm/version.py", line 108, in guess_next_version
    bumped = _bump_dev(version) or _bump_regex(version)
  File "/usr/lib/python3/dist-packages/setuptools_scm/version.py", line 128, in _bump_regex
    prefix, tail = re.match('(.*?)(\d+)$', version).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

Reading the PKG-INFO however does the job well and it will work in the tar.gz export as well when there is not .git directory present.

**Comment by ericzolf** [comment]
The thing is, it's the only job with this issue, so something is wrong with it. Could it be that you have setuptools installed via pip _and_ apt and they conflict with each other?

**Comment by ottok** [comment]
Nothing is installed via `pip`, I use clean Docker images for building to ensure there are no undocumented dependencies around.

**Comment by ericzolf** [comment]
By setting the variable `RUN_COMMAND=` to empty in `.travis.yml`, you've also decided to package outside of a "clean container" and are in the "dirty" container/VM of Travis, with whatever installed via pip (I just don't know what).

Sorry for being a pain but if we don't understand what we're doing, or why we're doing it, we're gathering technical debt and I'm always worried that too many workarounds and the same will bite us later.

**Comment by ericzolf** [comment]
OK, I captured the issue and will now merge before I'll push the next beta.

**Pull request merged**
