### PR TITLE
Fix cross device link error #519

### PR DESCRIPTION
**Pull request by ikus060**

### CODE REVIEW

**Comment by ericzolf** [comment]
Sorry, I didn't realize there was already a PR and I commented directly on the commit. Hope this is nevertheless clear.

**Comment by ericzolf** [comment]
Also improve your next commit message: add a `FIX: <meaningful message understandable by users>, closes #519` line so that it appears in the changelog.

**Comment by ikus060** [comment]
> Also improve your next commit message: add a `FIX: <meaningful message understandable by users>, closes #519` line so that it appears in the changelog.

done

**Review by ericzolf — CHANGES_REQUESTED** [review]
Sorry, commenting on the commit directly wasn't a good idea, it went lost as you pushed your last changes.

**Review by ericzolf — APPROVED** [review]

**Pull request merged**
