### PR TITLE
Sync librsyncmodule.c to latest version from upstream (Duplicity)

### PR DESCRIPTION
**Pull request by ottok**
Fetched from
https://bazaar.launchpad.net/~duplicity-team/duplicity/0.8-series/download/head:/duplicity_librsyncmo-20090223222003-21nplxjzl09x2a15-18/_librsyncmodule.c

### CODE REVIEW

**Comment by ericzolf** [comment]
Being curious _why_ we would want to merge this? Browsing through the differences, I don't understand the advantages (well, C isn't my strength).

Else, I'd like to have it rebased on master once my "bytes" branch has been merged, and then I can test and merge.

**Comment by ottok** [comment]
Using an age old librsyncmodule.c is not compatible with changes elsewhere, mainly librsync 2.0.2.

**Comment by ericzolf** [comment]
Actually, rdiff-backup is upstream to duplicity for this file. As part of the migration to Python3 I've done very similar changes in parallel, but anyway, it's been better maintained in recent years, if the tests are successful, I'll merge back.

**Comment by ericzolf** [comment]
There is an issue with the C-file, I can't get the specific librsync test to work.

This works:

```
$ git checkout master  # commit b3ab31fd344c08740d91f6a311890c3022abd07c
$ ./setup.py build
$ PATH=$PWD/build/scripts-3.7:$PATH PYTHONPATH=$PWD/build/lib.linux-x86_64-3.7 python3 testing/librsynctest.py
```

This doesn't work:

```
$ git checkout feature/sync-librsync-from-duplicity
$ ./setup.py build
$ PATH=$PWD/build/scripts-3.7:$PATH PYTHONPATH=$PWD/build/lib.linux-x86_64-3.7 python3 testing/librsynctest.py
```
Error message is:
```
librsync: ERROR: (rs_file_open) File exists "/home/elavarde/Public/rdiff-backup/build/testfiles/signature", aborting!
Flibrsync: ERROR: (rs_file_open) File exists "/home/elavarde/Public/rdiff-backup/build/testfiles/signature", aborting!
Flibrsync: ERROR: (rs_file_open) File exists "/home/elavarde/Public/rdiff-backup/build/testfiles/signature", aborting!
Flibrsync: ERROR: (rs_file_open) File exists "/home/elavarde/Public/rdiff-backup/build/testfiles/signature", aborting!
F.
======================================================================
FAIL: testDelta (__main__.LibrsyncTest)
Test delta generation by making sure rdiff can process output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/librsynctest.py", line 108, in testDelta
    (self.basis.path, self.sig.path))
AssertionError

======================================================================
FAIL: testPatch (__main__.LibrsyncTest)
Test patching against Rdiff
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/librsynctest.py", line 135, in testPatch
    (self.basis.path, self.sig.path))
AssertionError

======================================================================
FAIL: testSigFile (__main__.LibrsyncTest)
Make sure SigFile generates same data as rdiff, blocksize 512
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/librsynctest.py", line 49, in testSigFile
    self.sig_file_test_helper(512, 5)
  File "testing/librsynctest.py", line 36, in sig_file_test_helper
    (blocksize, self.basis.path, self.sig.path))
AssertionError

======================================================================
FAIL: testSigFile2 (__main__.LibrsyncTest)
Test SigFile like above, but try various blocksize
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/librsynctest.py", line 53, in testSigFile2
    self.sig_file_test_helper(2048, 1, 60000)
  File "testing/librsynctest.py", line 36, in sig_file_test_helper
    (blocksize, self.basis.path, self.sig.path))
AssertionError

----------------------------------------------------------------------
Ran 5 tests in 0.029s

FAILED (failures=4)
```

```

**Comment by ottok** [comment]
I did this change in downstream packaging where it was absolutely necessary to get the old rdiff-backup to build at all, see https://salsa.debian.org/python-team/applications/rdiff-backup/commit/29b7b904891c03fa14baa9c83cf9a3fb4dd7f405

I did this PR under the assumption that it would help here in upstream too, but if you say the Duplicity has copied it from rdiff-backup and syncing is not necessary, then we can close this PR. Maybe the new file is incompatible with the Python 3 code or something..

**Comment by ericzolf** [comment]
OK, we have enough open topics, I close.

**Pull request closed without merging**
